name: mern-app

services:
  backend:
    build: 
      context : ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 5000:5000
    env_file:
      - ./backend/.env
    networks:
      - mern-network

  frontend:
    build: 
      context : ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      - mern-network
    depends_on:
      - backend

networks:
  mern-network:
    driver: bridge
